import { BrowserProvider, Contract } from "ethers";
import type { JsonRpcSigner } from "ethers";
import type { ChainEntry } from "./stores/chainStore";

// contractConfig.json is generated by `npm run deploy` in the root project
// It contains the deployed contract address and ABI
let _config: { address: string; abi: object[] } | null = null;

export async function loadConfig() {
  if (_config) return _config;
  try {
    const mod = await import("./contractConfig.json");
    _config = mod.default as { address: string; abi: object[] };
    return _config;
  } catch {
    throw new Error(
      "contractConfig.json not found. Run `npm run deploy` in the project root first.",
    );
  }
}

function getContract(signerOrProvider: JsonRpcSigner | BrowserProvider) {
  if (!_config) throw new Error("Config not loaded. Call loadConfig() first.");
  return new Contract(_config.address, _config.abi, signerOrProvider);
}

// Read

export async function fetchAllEntries(
  provider: BrowserProvider,
): Promise<ChainEntry[]> {
  const contract = getContract(provider);
  const total = Number(await contract.getTotalEntries());
  const all: ChainEntry[] = [];

  for (let i = 0; i < total; i++) {
    const e = await contract.getEntry(i);
    all.push({
      id: Number(e.id),
      katakana: e.katakana,
      romaji: e.romaji,
      donorLanguage: e.donorLanguage,
      sourceWord: e.sourceWord,
      meaning: e.meaning,
      category: e.category,
      proposer: e.proposer,
      upvotes: Number(e.upvotes),
      downvotes: Number(e.downvotes),
      status: Number(e.status) as 0 | 1 | 2,
      timestamp: Number(e.timestamp),
    });
  }
  return all;
}

export async function checkHasVoted(
  provider: BrowserProvider,
  entryId: number,
  address: string,
): Promise<boolean> {
  const contract = getContract(provider);
  return contract.hasVoted(entryId, address);
}

export async function getContributorScore(
  provider: BrowserProvider,
  address: string,
): Promise<number> {
  const contract = getContract(provider);
  return Number(await contract.contributorScore(address));
}

// Write

export async function proposeEntry(
  signer: JsonRpcSigner,
  fields: {
    katakana: string;
    romaji: string;
    donorLanguage: string;
    sourceWord: string;
    meaning: string;
    category: string;
  },
): Promise<void> {
  const contract = getContract(signer);
  const tx = await contract.proposeEntry(
    fields.katakana,
    fields.romaji,
    fields.donorLanguage,
    fields.sourceWord,
    fields.meaning,
    fields.category,
  );
  await tx.wait();
}

export async function castVote(
  signer: JsonRpcSigner,
  entryId: number,
  upvote: boolean,
): Promise<void> {
  const contract = getContract(signer);
  const tx = await contract.vote(entryId, upvote);
  await tx.wait();
}

// Wallet

export async function connectWallet(): Promise<{
  provider: BrowserProvider;
  signer: JsonRpcSigner;
  account: string;
}> {
  if (!window.ethereum) {
    throw new Error(
      "MetaMask not found. Please install the MetaMask browser extension.",
    );
  }
  const browserProvider = new BrowserProvider(window.ethereum);
  await browserProvider.send("eth_requestAccounts", []);
  const s = await browserProvider.getSigner();
  const addr = await s.getAddress();
  return { provider: browserProvider, signer: s, account: addr };
}
